### PR TITLE
Update as-ffuf with error checking

### PR DESCRIPTION
**Pull request by loganjchris**
Add -sa option to automatically stop fuzzing if >95% 403s or spurious errors. Can also add -maxtime to hard cap fuzz time if wanted

### CODE REVIEW

**Review by defektive — APPROVED** [review]
lgtm

@NoF0rte did you want to look at this?

**Comment by NoF0rte** [comment]
The only issue I have is that the output files technically don't give any indication that errors occurred. Other than that, I think it is fine. Maybe the error thing can be dealt with some other time.

**Comment by NoF0rte** [comment]
@defektive What do you think about my previous comment? Should we just not care?

**Comment by NoF0rte** [comment]
@defektive I feel like I have a good solution. I made it so that when running `ffuf`, the StdErr is checked for warnings that `ffuf` puts when it quits from the different errors

**Review by NoF0rte — APPROVED** [review]

**Pull request merged**
